name: CLODIA
configurations:
  default: {}
modes:
  - key: bias
    name: Bias
    summary: Bias mode
    description: >
      Full description of the Bias mode
  - key: flat
    name: Flat
    summary: Flat mode
    description: >
      Full description of the Flat mode
  - key: image
    name: Image
    summary: Image mode
    description: >
      Full description of the Image mode
pipelines:
  default:
    version: 1
    recipes:
      bias: clodiadrp.recipes.recipe
      flat: clodiadrp.recipes.recipe
      image: clodiadrp.recipes.recipe